(TeX-add-style-hook
 "PythonAdvanced"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "a4paper" "12pt")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("geometry" "margin=2cm") ("inputenc" "utf8") ("ulem" "normalem") ("babel" "english") ("ctex" "UTF8" "heading") ("sourcecodepro" "default") ("fontenc" "T1")))
   (add-to-list 'LaTeX-verbatim-environments-local "Verbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "Verbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "BVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "BVerbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "LVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "LVerbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "SaveVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "VerbatimOut")
   (add-to-list 'LaTeX-verbatim-environments-local "lstlisting")
   (add-to-list 'LaTeX-verbatim-environments-local "minted")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Verb")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Verb*")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "lstinline")
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art12"
    "geometry"
    "hyperref"
    "inputenc"
    "fixltx2e"
    "graphicx"
    "longtable"
    "float"
    "wrapfig"
    "rotating"
    "ulem"
    "amsmath"
    "textcomp"
    "marvosym"
    "wasysym"
    "multicol"
    "amssymb"
    "listings"
    "babel"
    "ctex"
    "xltxtra"
    "xeCJK"
    "lmodern"
    "verbatim"
    "tikz"
    "soul"
    "listing"
    "algorithm"
    "algorithmic"
    "natbib"
    "fancyhdr"
    "fontspec"
    "xunicode"
    "CJKnumb"
    "amsfonts"
    "sourcecodepro"
    "fontenc"
    "color"
    "fancyvrb"
    "placeins"
    "xcolor"
    "enumitem")
   (LaTeX-add-labels
    "sec:orga07e762"
    "sec:org3f2f04e"
    "sec:org2c7d6a7"
    "sec:org8e37b34"
    "sec:org8ed5ee8"
    "org4c19c05"
    "sec:orgb4c6e2e"
    "sec:orgb56c16c"
    "orgcf376a7"
    "sec:org04a1943"
    "sec:orgfa2d593"
    "sec:org70ea444"
    "sec:org86f909a"
    "sec:org55bb8c5"
    "sec:orgf71149e"
    "sec:org169147b"
    "sec:orgbcbab74"
    "sec:org36ccbfa"
    "sec:orga1ecd77"
    "sec:org7925efd"
    "sec:org5aa9092"
    "sec:org1d45384"
    "org4c94a33"
    "sec:org2dd035d"
    "sec:orgc9f7a6d"
    "org06ada5a"
    "sec:orgd582d83"
    "sec:orgbb11694"
    "sec:orgd42575b"
    "sec:org735bfef"
    "sec:orgd0c7ed5"
    "sec:orgd698942"
    "sec:org018044b"
    "sec:orgf536542"
    "sec:org7a6cd8a"
    "sec:orgac84ccb"
    "fig:SimpleSin"
    "練習#1"
    "sec:org38dae65"
    "sec:orgcaca8f1"
    "sec:org852a1d4"
    "sec:org6dc9d50"
    "sec:orgb3daf7e"
    "fig:colors"
    "sec:org75d0cb9"
    "sec:org4dd358e"
    "sec:orgd56d3da"
    "練習#2"
    "sec:orgae61cce"
    "sec:org6d493a8"
    "sec:org5f5ba50"
    "sec:orgb98ca1c"
    "sec:org84c1ec0"
    "sec:orga07335c"
    "fig:SimplePie"
    "sec:org74744f7"
    "sec:orgde5ce73"
    "sec:org7e95564"
    "sec:orgb741829"
    "sec:orgf8a8265"
    "fig:SimpleSubplot"
    "sec:orge7aee58"
    "sec:org9ca7392"
    "sec:org16c6d6c"
    "sec:org21839a6"
    "sec:orgd375547"
    "sec:orgabc6bc5"
    "sec:orgdee299b"
    "sec:org3d87af6"
    "sec:orgac0531f"
    "sec:org939626e"
    "sec:orgfecc3ef"
    "sec:org034a419"
    "sec:org4e02265"
    "sec:orge596beb"
    "sec:orgcd54aab"
    "sec:org8f2eacb"
    "sec:orgd341ca5"
    "sec:org1fb691c"
    "sec:orgf06733d"
    "sec:org2ae1e98"
    "sec:org5b2c835"
    "sec:org5777d98"
    "sec:org03fa14d"
    "sec:orgd159f2e"
    "fig:PandasPlot-1"
    "sec:orgb956031"
    "fig:PandasPlot-2"
    "sec:orgd79eea7"
    "fig:PandasPlot-3"
    "sec:orgbe2dc84"
    "fig:PandasPlot-4"
    "sec:org12b4004"
    "sec:org2df8ecb"
    "sec:org661982b"
    "sec:orgcaf65df"
    "sec:org38f2583"
    "sec:orgf9bc96a"
    "sec:org7635f7d"
    "sec:org4c5dfb6"
    "fig:jsonLine"
    "sec:org9dd86fe"
    "fig:jsonBar"
    "sec:org935ab83"
    "sec:org0290b02"
    "sec:orgf68e1c7"
    "sec:org14e850c"
    "sec:orga5dcf77"
    "sec:org39b4ba1"
    "sec:org32119e7"
    "sec:orgb359a3e"
    "sec:orgbc0fdbe"
    "sec:orgc560732"
    "sec:orgc4f2b62"
    "sec:orgfe7b27c"
    "sec:orgfa094d0"
    "sec:org32f221d"
    "sec:orga753e7c")
   (LaTeX-add-xcolor-definecolors
    "dkgreen"
    "dred"
    "dblue"
    "lgrey"
    "gray"
    "darkblue"
    "bubbles"
    "foreground"
    "background"
    "preprocess"
    "var"
    "string"
    "type"
    "function"
    "keyword"
    "comment"
    "doc"
    "comdil"
    "constant"))
 :latex)

