(TeX-add-style-hook
 "PythonAdvanced"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "a4paper" "12pt")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("geometry" "margin=2cm") ("inputenc" "utf8") ("ulem" "normalem") ("babel" "english") ("ctex" "UTF8" "heading") ("sourcecodepro" "default") ("fontenc" "T1")))
   (add-to-list 'LaTeX-verbatim-environments-local "Verbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "Verbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "BVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "BVerbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "LVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "LVerbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "SaveVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "VerbatimOut")
   (add-to-list 'LaTeX-verbatim-environments-local "lstlisting")
   (add-to-list 'LaTeX-verbatim-environments-local "minted")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Verb")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Verb*")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "lstinline")
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art12"
    "geometry"
    "hyperref"
    "inputenc"
    "fixltx2e"
    "graphicx"
    "longtable"
    "float"
    "wrapfig"
    "rotating"
    "ulem"
    "amsmath"
    "textcomp"
    "marvosym"
    "wasysym"
    "multicol"
    "amssymb"
    "listings"
    "babel"
    "ctex"
    "xltxtra"
    "xeCJK"
    "lmodern"
    "verbatim"
    "tikz"
    "soul"
    "listing"
    "algorithm"
    "algorithmic"
    "natbib"
    "fancyhdr"
    "fontspec"
    "xunicode"
    "CJKnumb"
    "amsfonts"
    "sourcecodepro"
    "fontenc"
    "color"
    "fancyvrb"
    "placeins"
    "xcolor"
    "enumitem")
   (LaTeX-add-labels
    "sec:org2cbf47c"
    "sec:org242f2ac"
    "sec:orgbd71f83"
    "sec:orgf354665"
    "sec:orga3b02ef"
    "org2570cf1"
    "sec:orgdf352fe"
    "sec:org3c89092"
    "orgc94b9ba"
    "sec:org626dd5e"
    "sec:orge991fc8"
    "sec:orge2548fd"
    "sec:org108326c"
    "sec:org7eb6ca5"
    "sec:org48811c1"
    "sec:org8fd53a1"
    "sec:orgdbcf9ef"
    "sec:orgd10cfa2"
    "sec:org6572af2"
    "sec:org5287b33"
    "sec:orgc357f7e"
    "sec:org4b5821b"
    "org723ef49"
    "sec:orgd11d5ea"
    "sec:orgcf0d00d"
    "org75002a8"
    "sec:org4e134be"
    "sec:org951a7a7"
    "sec:orgdf0a2e1"
    "sec:org85f1e9a"
    "sec:orgc927df4"
    "sec:orgdce42ae"
    "sec:org0d66152"
    "sec:org2b1948d"
    "sec:org6fff813"
    "sec:orga50fcd6"
    "fig:SimpleSin"
    "練習#1"
    "sec:org1559963"
    "sec:org8d5c06d"
    "sec:orgd553e02"
    "sec:orgf8341cc"
    "sec:org9d0d765"
    "fig:colors"
    "sec:orgd566798"
    "sec:org685eefc"
    "sec:org93c3bf1"
    "練習#2"
    "sec:orgc2a051c"
    "sec:org2ead3d1"
    "sec:orgfbfb261"
    "sec:orgac20225"
    "sec:org84e02e6"
    "sec:orge7050a0"
    "fig:SimplePie"
    "sec:orgbf76c90"
    "sec:orgc83dbd9"
    "sec:orgaa7d6b2"
    "sec:org54fc670"
    "sec:org7e1ac16"
    "fig:SimpleSubplot"
    "sec:org089a473"
    "sec:org8ec673c"
    "sec:org3c37364"
    "sec:orgc0a041c"
    "sec:org6aa9dcc"
    "sec:orgb7533f7"
    "sec:org1372b1c"
    "sec:org3dc2f11"
    "sec:org94243b4"
    "sec:org759d6ae"
    "sec:org7406725"
    "sec:orgf51ec8d"
    "sec:orgbd59884"
    "sec:org97b007b"
    "sec:orgb21f495"
    "sec:orgdff93d5"
    "sec:orgc1c13a3"
    "sec:org966c789"
    "sec:org8362dac"
    "sec:org765a289"
    "sec:orgcb82926"
    "sec:org1cf0703"
    "sec:org724cb73"
    "sec:org9567fa1"
    "fig:PandasPlot-1"
    "sec:orgd058e7d"
    "fig:PandasPlot-2"
    "sec:org81b61f9"
    "fig:PandasPlot-3"
    "sec:org03cc8da"
    "fig:PandasPlot-4"
    "sec:org1925e60"
    "sec:orge09cf5a"
    "sec:org29a1e3b"
    "sec:orgee8f9bc"
    "sec:orga57cf01"
    "sec:orgfec6e3f"
    "sec:org0e18070"
    "sec:org17ef5df"
    "fig:jsonLine"
    "sec:org0bdd32d"
    "fig:jsonBar"
    "sec:org39fc0e3"
    "sec:org6b82469"
    "sec:orgb587186"
    "sec:orgdebe19c"
    "sec:orga3d9a2e"
    "sec:orga6f41bf"
    "sec:org70be7b1"
    "sec:org4c16e12"
    "sec:org1b72aff"
    "sec:org54fc7ae"
    "sec:orgf137b14"
    "sec:orgcf3df7d"
    "sec:org0354c56"
    "sec:org0daa1d1"
    "sec:orgfd91c4b")
   (LaTeX-add-xcolor-definecolors
    "dkgreen"
    "dred"
    "dblue"
    "lgrey"
    "gray"
    "darkblue"
    "bubbles"
    "foreground"
    "background"
    "preprocess"
    "var"
    "string"
    "type"
    "function"
    "keyword"
    "comment"
    "doc"
    "comdil"
    "constant"))
 :latex)

