(TeX-add-style-hook
 "PythonAdvanced"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "a4paper" "12pt")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("geometry" "margin=2cm") ("inputenc" "utf8") ("ulem" "normalem") ("babel" "english") ("ctex" "UTF8" "heading") ("sourcecodepro" "default") ("fontenc" "T1")))
   (add-to-list 'LaTeX-verbatim-environments-local "minted")
   (add-to-list 'LaTeX-verbatim-environments-local "lstlisting")
   (add-to-list 'LaTeX-verbatim-environments-local "VerbatimOut")
   (add-to-list 'LaTeX-verbatim-environments-local "SaveVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "LVerbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "LVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "BVerbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "BVerbatim")
   (add-to-list 'LaTeX-verbatim-environments-local "Verbatim*")
   (add-to-list 'LaTeX-verbatim-environments-local "Verbatim")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "lstinline")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Verb*")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "Verb")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art12"
    "geometry"
    "hyperref"
    "inputenc"
    "fixltx2e"
    "graphicx"
    "longtable"
    "float"
    "wrapfig"
    "rotating"
    "ulem"
    "amsmath"
    "textcomp"
    "marvosym"
    "wasysym"
    "multicol"
    "amssymb"
    "listings"
    "babel"
    "ctex"
    "xltxtra"
    "xeCJK"
    "lmodern"
    "verbatim"
    "tikz"
    "soul"
    "listing"
    "algorithm"
    "algorithmic"
    "natbib"
    "fancyhdr"
    "fontspec"
    "xunicode"
    "CJKnumb"
    "amsfonts"
    "sourcecodepro"
    "fontenc"
    "color"
    "fancyvrb"
    "placeins"
    "xcolor"
    "enumitem")
   (LaTeX-add-labels
    "sec:org6ccb8a1"
    "sec:org3f62d60"
    "sec:org1ddac62"
    "sec:orgbf86431"
    "sec:orgfe277ac"
    "org8e57d22"
    "sec:org8f0ffa4"
    "sec:org70d815e"
    "org4c249cc"
    "sec:org17b637a"
    "sec:org1289690"
    "sec:orge678943"
    "sec:orgb16667a"
    "sec:org78ca08d"
    "sec:org70dbd2a"
    "sec:org8c0eb42"
    "sec:org6f4b51b"
    "sec:org3ecdf84"
    "sec:org1540279"
    "sec:orga94a660"
    "sec:org49d8c5f"
    "sec:orge9ef4d4"
    "orgb6cecbd"
    "sec:org744cb8c"
    "sec:org6ce362a"
    "org126d7e7"
    "sec:orgc85edf9"
    "sec:orgeba1a6c"
    "sec:org2ca5096"
    "sec:orgb5a5717"
    "sec:org9923dcc"
    "sec:orgb1d2cb6"
    "sec:orgda78780"
    "sec:org58ef8ed"
    "sec:orgf01cec1"
    "sec:org045648c"
    "sec:org418915d"
    "fig:SimpleSin"
    "練習#1"
    "sec:org9c8f8dc"
    "sec:org8fc28b0"
    "sec:orge526311"
    "sec:org3996ea5"
    "sec:org08ebb8d"
    "fig:colors"
    "sec:org5610163"
    "sec:org7e64faa"
    "sec:org677b4a4"
    "練習#2"
    "sec:org43ece9b"
    "sec:orgf8c9c33"
    "sec:org4cbbee7"
    "sec:org4404ff1"
    "sec:org42f0914"
    "sec:org85455f7"
    "fig:SimplePie"
    "sec:orgead3a49"
    "sec:org0c517d4"
    "sec:orgb6ab3ee"
    "sec:org37f3b96"
    "sec:org1de317b"
    "fig:SimpleSubplot"
    "sec:org4b27582"
    "sec:org021940b"
    "sec:orgfc2e32c"
    "sec:org544343e"
    "sec:org93fac5e"
    "sec:orgd999328"
    "sec:orge3ef837"
    "sec:org6d08fcb"
    "sec:orgb36a736"
    "sec:org273558b"
    "sec:orgfe53a3e"
    "sec:orgc0f4edf"
    "sec:orgca52a9c"
    "sec:org0a068aa"
    "sec:org243d170"
    "sec:org2e59a1c"
    "sec:orga3166ce"
    "sec:org059091f"
    "sec:orgf4b8156"
    "sec:org77f3503"
    "sec:org11fd15e"
    "sec:orged5e281"
    "sec:org283a70c"
    "sec:org00a8e9a"
    "sec:orgadbdc58"
    "fig:PandasPlot-1"
    "sec:org26a194d"
    "fig:PandasPlot-2"
    "sec:orge538564"
    "fig:PandasPlot-3"
    "sec:orgfa40b6a"
    "fig:PandasPlot-4"
    "sec:org5baa1c5"
    "sec:org3e91e4a"
    "sec:org8f1154f"
    "sec:org79edee5"
    "sec:org9c5e519"
    "sec:org87af589"
    "sec:orgdd667dc"
    "sec:orgbdd9054"
    "sec:orge043d54"
    "fig:jsonLine"
    "sec:org862b1d2"
    "fig:jsonBar"
    "sec:org9e5e634"
    "sec:org05a7fb8"
    "sec:org84031a0"
    "sec:org250fd93"
    "sec:org6617812"
    "sec:org650470f"
    "sec:org5e8fdb5"
    "sec:org0979c64"
    "sec:org0973906"
    "sec:org9850d73"
    "sec:org4075439"
    "sec:org0f5f217"
    "sec:orgeb1ec62"
    "sec:org072068d"
    "sec:orgfa27d06"
    "sec:org4daa2a0"
    "sec:org6f24b16"
    "sec:orgc0cdf12")
   (LaTeX-add-xcolor-definecolors
    "dkgreen"
    "dred"
    "dblue"
    "lgrey"
    "gray"
    "darkblue"
    "bubbles"
    "foreground"
    "background"
    "preprocess"
    "var"
    "string"
    "type"
    "function"
    "keyword"
    "comment"
    "doc"
    "comdil"
    "constant"))
 :latex)

